name: Build Love2D with Lua 5.4.8

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

env:
  LOVE2D_REPO: "https://github.com/love2d/love.git"
  LOVE2D_BRANCH: "main"
  LUA_VERSION: "5.4.8"

permissions:
  contents: write
  packages: write

jobs:
  version:
    name: Determine Love2D version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}
      padded_build: ${{ steps.get-version.outputs.padded_build }}
      commit_hash: ${{ steps.get-version.outputs.commit_hash }}

    steps:
    - name: Get version and commit info
      id: get-version
      run: |
        # Clone Love2D to get commit hash
        git clone --depth 1 --branch ${{ env.LOVE2D_BRANCH }} ${{ env.LOVE2D_REPO }} love2d-temp
        COMMIT_HASH=$(git -C love2d-temp rev-parse --short HEAD)
        echo "version=$(date "+%Y.%m.%d")" >> $GITHUB_OUTPUT
        echo "padded_build=$(printf '%05d' ${{ github.run_number }})" >> $GITHUB_OUTPUT
        echo "commit_hash=$COMMIT_HASH" >> $GITHUB_OUTPUT
        rm -rf love2d-temp

  Windows-Lua548:
    runs-on: windows-2025
    needs: version
    env: 
      ALSOFT_CONF: megasource/libs/love/testing/resources/alsoft.conf
    strategy:
      matrix:
        platform: [x64, ARM64]
    defaults:
      run:
        shell: cmd
    continue-on-error: ${{ matrix.platform == 'ARM64' }}
    steps:
    - name: Define Variables
      id: vars
      run: |
        rem Architecture-Specific Switch
        goto ${{ matrix.platform }}
        exit /b 1
        
        :x64
        (echo arch=x64)>> "%GITHUB_OUTPUT%"
        (echo angle=0)>> "%GITHUB_OUTPUT%"
        echo nofiles=warn>> "%GITHUB_OUTPUT%"
        exit /b 0
        
        :ARM64
        (echo arch=arm64)>> "%GITHUB_OUTPUT%"
        (echo angle=1)>> "%GITHUB_OUTPUT%"
        echo nofiles=ignore>> "%GITHUB_OUTPUT%"
        echo moredef=-DLOVE_EXTRA_DLLS=%CD%\angle\libEGL.dll;%CD%\angle\libGLESv2.dll>> "%GITHUB_OUTPUT%"
        exit /b 0

    - name: Install NSIS
      run: winget install nsis --disable-interactivity --accept-source-agreements --accept-package-agreements

    - name: Download pdbstr
      run: curl -Lfo pdbstr.nupkg https://www.nuget.org/api/v2/package/Microsoft.Debugging.Tools.PdbStr/20230731.1609.0

    - name: Download srctool
      run: curl -Lfo srctool.nupkg https://www.nuget.org/api/v2/package/Microsoft.Debugging.Tools.SrcTool/20230731.1609.0

    - name: Extract Tools and Add to PATH
      run: |
        mkdir debugtools
        cd debugtools
        if errorlevel 1 exit /b 1
        7z e ..\srctool.nupkg content/amd64/srctool.exe
        if errorlevel 1 exit /b 1
        7z e ..\pdbstr.nupkg content/amd64/pdbstr.exe
        if errorlevel 1 exit /b 1
        echo %CD%>>%GITHUB_PATH%

    - name: Setup Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Download source_index.py
      run: curl -Lfo source_index.py https://gist.github.com/MikuAuahDark/d9c099f5714e09a765496471c2827a55/raw/df34956052035f3473c5f01861dfb53930d06843/source_index.py

    - name: Clone Megasource
      uses: actions/checkout@v4
      with:
        path: megasource
        repository: love2d/megasource
        ref: main

    - id: megasource
      name: Get Megasource Commit SHA
      shell: python
      run: |
        import os
        import subprocess
        
        result = subprocess.run("git -C megasource rev-parse HEAD".split(), check=True, capture_output=True, encoding="UTF-8")
        commit = result.stdout.split()[0]
        with open(os.environ["GITHUB_OUTPUT"], "w", encoding="UTF-8") as f: f.write(f"commit={commit}")

    - name: Checkout Love2D
      run: |
        git clone --recursive ${{ env.LOVE2D_REPO }} megasource/libs/love
        cd megasource/libs/love
        git checkout ${{ env.LOVE2D_BRANCH }}

    - name: Patch Love2D for Lua 5.4 compatibility
      shell: python
      run: |
        import os
        import re
        
        # Patch wrap_Event.cpp - replace lua_cpcall with lua_pcall
        wrap_event = "megasource/libs/love/src/modules/event/wrap_Event.cpp"
        print(f"[1/1] Patching {wrap_event} for Lua 5.4...")
        
        if not os.path.exists(wrap_event):
            print(f"[ERROR] File not found: {wrap_event}")
            import sys
            sys.exit(1)
        
        with open(wrap_event, 'r', encoding='utf-8') as f:
            content = f.read()
        
        # Debug: Show file size
        print(f"[DEBUG] File size: {len(content)} bytes")
        
        # Check if lua_cpcall exists in the file
        if 'lua_cpcall' not in content:
            print("[INFO] No lua_cpcall found - file may already be Lua 5.4 compatible")
            print("[SKIP] No patching needed")
        else:
            print("[DEBUG] Found lua_cpcall in file")
            
            # Count occurrences
            count = content.count('lua_cpcall')
            print(f"[DEBUG] Found {count} occurrence(s) of lua_cpcall")
            
            # Use regex to replace all lua_cpcall occurrences
            # Pattern: lua_cpcall(L, function_name, argument)
            # Capture groups: (function_name) and (argument)
            pattern = r'int err = lua_cpcall\s*\(\s*L\s*,\s*(\w+)\s*,\s*([^)]+)\s*\)'
            replacement = r'lua_pushcfunction(L, \1); lua_pushlightuserdata(L, \2); int err = lua_pcall(L, 1, 0, 0)'
            
            # Apply patch
            new_content, num_replacements = re.subn(pattern, replacement, content)
            
            if num_replacements == 0:
                print("[ERROR] Pattern matching failed - no replacements made")
                # Try to find the actual pattern
                if 'lua_cpcall' in content:
                    idx = content.find('lua_cpcall')
                    context = content[max(0, idx-50):min(len(content), idx+100)]
                    print(f"[DEBUG] Context around lua_cpcall:\n{context}")
                import sys
                sys.exit(1)
            
            # Write patched content
            with open(wrap_event, 'w', encoding='utf-8') as f:
                f.write(new_content)
            
            print(f"[OK] Patched {num_replacements} occurrence(s) of lua_cpcall -> lua_pcall")
            
            # Verify patch
            with open(wrap_event, 'r', encoding='utf-8') as f:
                verify_content = f.read()
            
            if 'lua_cpcall' in verify_content:
                print("[ERROR] Verification failed - lua_cpcall still exists after patch!")
                import sys
                sys.exit(1)
            
            if 'lua_pushcfunction' not in verify_content:
                print("[ERROR] Verification failed - lua_pushcfunction not found after patch!")
                import sys
                sys.exit(1)
            
            print("[VERIFIED] Patch successfully applied and verified")

    - name: Replace Lua 5.1.5 with Lua 5.4.8
      shell: python
      run: |
        import os
        import urllib.request
        import tarfile
        import shutil
        
        lua_version = "${{ env.LUA_VERSION }}"
        
        print(f"[1/5] Downloading Lua {lua_version}...")
        url = f"https://www.lua.org/ftp/lua-{lua_version}.tar.gz"
        tar_path = f"lua-{lua_version}.tar.gz"
        urllib.request.urlretrieve(url, tar_path)
        
        print("[2/5] Extracting Lua source...")
        with tarfile.open(tar_path, 'r:gz') as tar:
            tar.extractall()
        
        old_lua = "megasource/libs/lua-5.1.5"
        print(f"[3/5] Removing {old_lua}...")
        if os.path.exists(old_lua):
            shutil.rmtree(old_lua)
        
        print(f"[4/5] Renaming lua-{lua_version} to lua-5.1.5...")
        shutil.move(f"lua-{lua_version}", old_lua)
        
        print("[5/5] Creating CMakeLists.txt for Lua 5.4.8...")
        cmake_path = os.path.join(old_lua, 'CMakeLists.txt')
        with open(cmake_path, 'w', encoding='utf-8') as f:
            f.write('cmake_minimum_required(VERSION 2.8)\n\n')
            f.write('project(lua51)\n\n')
            f.write('option(LUA_BUILD_SHARED "Build shared library" ON)\n')
            f.write('option(LUA_BUILD_STATIC "Build static library" OFF)\n\n')
            f.write('set(LUA_SRC\n')
            f.write('\tsrc/lapi.c\n')
            f.write('\tsrc/lauxlib.c\n')
            f.write('\tsrc/lbaselib.c\n')
            f.write('\tsrc/lcode.c\n')
            f.write('\tsrc/lcorolib.c\n')
            f.write('\tsrc/lctype.c\n')
            f.write('\tsrc/ldblib.c\n')
            f.write('\tsrc/ldebug.c\n')
            f.write('\tsrc/ldo.c\n')
            f.write('\tsrc/ldump.c\n')
            f.write('\tsrc/lfunc.c\n')
            f.write('\tsrc/lgc.c\n')
            f.write('\tsrc/linit.c\n')
            f.write('\tsrc/liolib.c\n')
            f.write('\tsrc/llex.c\n')
            f.write('\tsrc/lmathlib.c\n')
            f.write('\tsrc/lmem.c\n')
            f.write('\tsrc/loadlib.c\n')
            f.write('\tsrc/lobject.c\n')
            f.write('\tsrc/lopcodes.c\n')
            f.write('\tsrc/loslib.c\n')
            f.write('\tsrc/lparser.c\n')
            f.write('\tsrc/lstate.c\n')
            f.write('\tsrc/lstring.c\n')
            f.write('\tsrc/lstrlib.c\n')
            f.write('\tsrc/ltable.c\n')
            f.write('\tsrc/ltablib.c\n')
            f.write('\tsrc/ltm.c\n')
            f.write('\tsrc/lundump.c\n')
            f.write('\tsrc/lutf8lib.c\n')
            f.write('\tsrc/lvm.c\n')
            f.write('\tsrc/lzio.c\n')
            f.write(')\n\n')
            f.write('if (LUA_BUILD_STATIC)\n')
            f.write('\tadd_library(lua51-static STATIC ${LUA_SRC})\n')
            f.write('\ttarget_include_directories(lua51-static PUBLIC src)\n')
            f.write('endif()\n\n')
            f.write('if (LUA_BUILD_SHARED)\n')
            f.write('\tadd_library(lua51 SHARED ${LUA_SRC})\n')
            f.write('\ttarget_include_directories(lua51 PUBLIC src)\n')
            f.write('\tif(MSVC)\n')
            f.write('\t\tset_property(TARGET lua51 PROPERTY COMPILE_DEFINITIONS LUA_BUILD_AS_DLL=1)\n')
            f.write('\tendif()\n')
            f.write('\tinstall(TARGETS lua51 RUNTIME DESTINATION . LIBRARY DESTINATION .)\n')
            f.write('endif()\n')
        
        print("\n[SUCCESS] Lua 5.4.8 replacement complete!")
        print(f"  Directory: {old_lua} (contains Lua {lua_version})")
        print(f"  CMakeLists.txt: Created")
        print(f"  Target: lua51")
        print(f"  Output: lua51.dll (internal: Lua {lua_version})")
        
        # Verify critical files
        errors = []
        if not os.path.exists(cmake_path):
            errors.append("CMakeLists.txt NOT created")
        if not os.path.exists(os.path.join(old_lua, 'src', 'lcorolib.c')):
            errors.append("lcorolib.c (Lua 5.4 file) NOT found")
        if not os.path.exists(os.path.join(old_lua, 'src', 'lutf8lib.c')):
            errors.append("lutf8lib.c (Lua 5.4 file) NOT found")
        if os.path.exists(os.path.join(old_lua, 'src', 'print.c')):
            errors.append("print.c (Lua 5.1 file) still exists - should not be there")
        
        if errors:
            print("\n[ERROR] Verification failed:")
            for err in errors:
                print(f"  - {err}")
            import sys
            sys.exit(1)
        else:
            print("\n[VERIFIED] All critical files present and correct")

    - name: Download ANGLE
      uses: robinraju/release-downloader@v1.9
      if: steps.vars.outputs.angle == '1'
      with:
        repository: MikuAuahDark/angle-winbuild
        tag: cr_5249
        fileName: angle-win-${{ steps.vars.outputs.arch }}.zip
        tarBall: false
        zipBall: false
        out-file-path: angle

    - name: Extract ANGLE
      if: steps.vars.outputs.angle == '1'
      working-directory: angle
      run: 7z x angle-win-${{ steps.vars.outputs.arch }}.zip

    - name: Remove Strawberry Perl From Path
      run: |
        move /y C:\Strawberry C:\Strawberry_not_in_PATH
        exit /b 0

    - name: Configure
      env:
        CFLAGS: /Zi
        CXXFLAGS: /Zi
        LDFLAGS: /DEBUG:FULL /OPT:REF /OPT:ICF
      run: cmake -Bbuild -Smegasource -T v143 -A ${{ matrix.platform }},version=10.0.26100.0 --install-prefix %CD%\install -DCMAKE_PDB_OUTPUT_DIRECTORY=%CD%\pdb -DLOVE_JIT=OFF ${{ steps.vars.outputs.moredef }}

    - name: Install
      run: cmake --build build --target PACKAGE --config Release -j2

    - name: Copy Lua 5.4 lua51.pdb
      run: |
        copy /Y build\lua51\lua51.pdb pdb\Release\lua51.pdb
        exit /b 0

    - name: Add srcsrv to PATH
      run: |
        echo C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\srcsrv>>%GITHUB_PATH%

    - name: Embed Source Index into PDBs
      run: |
        python source_index.py ^
        --source %CD%\megasource\libs\love https://raw.githubusercontent.com/love2d/love/${{ needs.version.outputs.commit_hash }} ^
        --source %CD%\megasource https://raw.githubusercontent.com/love2d/megasource/${{ steps.megasource.outputs.commit }} ^
        --source %CD%\megasource\libs\lua-5.1.5 https://www.lua.org/ftp/ ^
        pdb\Release\*.pdb

    - name: Artifact
      uses: actions/upload-artifact@v4
      with:
        name: love-windows-${{ steps.vars.outputs.arch }}-lua548
        path: |
          build/*.zip
          build/*.exe
        if-no-files-found: ${{ steps.vars.outputs.nofiles }}

    - name: Artifact PDB
      uses: actions/upload-artifact@v4
      with:
        name: love-windows-${{ steps.vars.outputs.arch }}-lua548-dbg
        path: pdb/Release/*.pdb

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [version, Windows-Lua548]
    if: (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && !cancelled()

    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4

    - name: Prepare release files
      run: |
        # Create release directory
        mkdir -p release-files
        
        # Copy files from each artifact directory
        for dir in love-windows-*-lua548; do
          if [ -d "$dir" ] && [[ "$dir" != *"-dbg" ]]; then
            echo "Processing directory: $dir"
            find "$dir" -type f \( -name "*.zip" -o -name "*.exe" \) | while read file; do
              basename_file=$(basename "$file")
              if [[ "$dir" == *"x64"* ]]; then
                arch="x64"
              elif [[ "$dir" == *"arm64"* ]]; then
                arch="arm64"  
              fi
              ext="${basename_file##*.}"
              cp "$file" "release-files/love-${{ needs.version.outputs.version }}-lua548-build${{ needs.version.outputs.padded_build }}-windows-${arch}.${ext}"
            done
          fi
        done
        
        # List what we have
        echo "Files to be released:"
        ls -la release-files/

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: release-files/*
        tag_name: v${{ needs.version.outputs.version }}-lua548-build-${{ needs.version.outputs.padded_build }}
        name: Love2D ${{ needs.version.outputs.version }} with Lua 5.4.8 Build ${{ needs.version.outputs.padded_build }}
        body: |
          Automated build of Love2D ${{ needs.version.outputs.version }} with **Lua 5.4.8** for Windows

          Built from upstream Love2D repository
          Build number: ${{ needs.version.outputs.padded_build }}
          Commit: ${{ needs.version.outputs.commit_hash }}
          Repository: ${{ env.LOVE2D_REPO }}
          Branch: ${{ env.LOVE2D_BRANCH }}
          Lua Version: ${{ env.LUA_VERSION }}

          **Downloads:**
          - Windows x64: `love-${{ needs.version.outputs.version }}-lua548-build${{ needs.version.outputs.padded_build }}-windows-x64.zip`
          - Windows ARM64: `love-${{ needs.version.outputs.version }}-lua548-build${{ needs.version.outputs.padded_build }}-windows-arm64.zip` (if available)

          **Important Notes:**
          - This build uses **Lua 5.4.8** instead of LuaJIT
          - DLL name is `lua51.dll` for compatibility (internal version is Lua 5.4.8)
          - Verify with `print(_VERSION)` in Love2D (should output "Lua 5.4")
          - No JIT compilation - pure Lua 5.4 interpreter
          - May have different performance and API behavior compared to LuaJIT builds

          This build includes:
          - Love2D Game Framework
          - Lua 5.4.8 runtime (as lua51.dll)
          - All required runtime libraries
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
